### ISSUE TITLE
Can't select or open USB device in Python 3.8

### ISSUE THREAD

**Issue by thladnik** [TheImagingSource/Linux-tiscamera-Programming-Samples#14]
Hi, 

I've compiled and installed the tiscamera SDK on my system (Ubuntu 20.04) and everything seems to be working fine. I can detect, select and control cameras with the tcam-capture and tcam-ctrl utilities. 

But I haven't been able to get any of the Python examples with GStreamer to work so far. When I, for example, try to use TIS.selectDevice() with

```
import TIS
Tis = TIS.TIS()

if not Tis.selectDevice():
    quit(0)
```
I get the following exception:
```
Traceback (most recent call last):
  File "path/snap_image.py", line 8, in <module>
    if not Tis.selectDevice():
  File "path/TIS.py", line 277, in selectDevice
    serials = source.get_device_serials()
AttributeError: 'NoneType' object has no attribute 'get_device_serials'
```

When I directly try to open a device with
```
import TIS

Tis = TIS.TIS()
Tis = Tis.openDevice('sn', 640, 480, '30/1', TIS.SinkFormats.BGRA, True)
```

I get:
```
(process:10200): GStreamer-CRITICAL **: 10:24:14.029: gst_element_factory_make: assertion 'gst_is_initialized ()' failed
Traceback (most recent call last):
  File "path/open_device.py", line 4, in <module>
    Tis = Tis.openDevice('25610433', 640, 480, '30/1', TIS.SinkFormats.BGRA, True)
  File "path/TIS.py", line 80, in openDevice
    self._createPipeline()
  File "path/TIS.py", line 94, in _createPipeline
    self.pipeline = Gst.parse_launch(p)
gi.repository.GLib.Error: gst_parse_error: no element "tcambin" (1)

Process finished with exit code 1
```

This is the minimal Python 3.8 environment I'm trying to use:
```
gst-python-stubs 0.0.2
numpy            1.21.2
opencv-python    4.5.3.56
pip              21.1.2
pycairo          1.20.1
PyGObject        3.40.1
PyGObject-stubs  0.0.2
setuptools       57.0.0
wheel            0.36.2
```

What may be the cause of this?

**Comment by TIS-Edgar** [comment]
It seems there is a mistake in TIS.py.

Can you try to add `Gst.init([])` before the line `DeviceInfo = namedtuple("DeviceInfo", "status name identifier connection_type")`.
in the file python-common/TIS.py.

**Comment by thladnik** [comment]
That fixed it. It works now! Thanks!
